baseURL = "https://xcamier.github.io/devExplorerBlog/"
title = "Code & Technics"
copyright = "Copyright © 2020, Xavier Camier; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = ""
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Xavier Camier"
  description = "Code & Technics Exploration Blog"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "camierxthrow@icloud.com"
    facebook = ""
    linkedin = "https://www.linkedin.com/in/xavier-camier-35b0445b"
    github = "https://github.com/xcamier"

  [params.prismJS]
    enable = false
    theme = "okaidia"

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true